TONYN_STALLONE = "Tonyn Stallone"
ARNALDOR_SHUATSENEGUER = "Arnaldor Shuatseneguer"

TALADOKEN = "Taladoken"
REMUYUKEN = "Remuyuken"
PUNCH = "Puño"
KICK = "Patada"

TONYN_STALLONE_HIT_1 = "DSD+P"
TONYN_STALLONE_HIT_2 = "SD+K"
TONYN_STALLONE_HIT_3 = "+P"
TONYN_STALLONE_HIT_4 = "+K"

ARNALDOR_SHUATSENEGUER_HIT_1 = "ASA+P"
ARNALDOR_SHUATSENEGUER_HIT_2 = "SA+K"
ARNALDOR_SHUATSENEGUER_HIT_3 = "+P"
ARNALDOR_SHUATSENEGUER_HIT_4 = "+K"

HIT_COMBINATION_TONYN_STALLONE = {
    TONYN_STALLONE_HIT_1: [3, TALADOKEN],
    TONYN_STALLONE_HIT_2: [3, REMUYUKEN],
    TONYN_STALLONE_HIT_3: [1, PUNCH],
    TONYN_STALLONE_HIT_4: [1, KICK],
}

HIT_COMBINATION_ARNALDOR_SHUATSENEGUER = {
    ARNALDOR_SHUATSENEGUER_HIT_1: [3, TALADOKEN],
    ARNALDOR_SHUATSENEGUER_HIT_2: [3, REMUYUKEN],
    ARNALDOR_SHUATSENEGUER_HIT_3: [1, PUNCH],
    ARNALDOR_SHUATSENEGUER_HIT_4: [1, KICK],
}

MOVEMENTS = {
    "W": "se mueve hacia arriba ",
    "A": "se mueve a la izquierda ",
    "S": "se mueve hacia abajo ",
    "D": "se mueve a la derecha ",
}
